const CardsActionTypes = {
  FETCH_CARDS_START: "FETCH_CARDS_START",
  FETCH_CARDS_SUCCESS: "FETCH_CARDS_SUCCESS",
  FETCH_CARDS_FAILURE: "FETCH_CARDS_FAILURE",
  DELETE_CARD: "DELETE_CARD",
  ADD_CARD: "ADD_CARD",
};

export default CardsActionTypes;
