const AddCardActionTypes = {
  CARD_ADD_START: "CARD_ADD_START",
  CARD_ADD_SUCCESS: "CARD_ADD_SUCCESS",
  CARD_ADD_FAILURE: "CARD_ADD_FAILURE",
  IMAGE_ADD_START: "IMAGE_ADD_START",
  IMAGE_ADD_SUCCESS: "IMAGE_ADD_SUCCESS",
  IMAGE_ADD_FAILURE: "IMAGE_ADD_FAILURE",
};

export default AddCardActionTypes;
